/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface WopVincentImg {
      'dataSrc': string;
    }
  }

  interface HTMLWopVincentImgElement extends StencilComponents.WopVincentImg, HTMLStencilElement {}

  var HTMLWopVincentImgElement: {
    prototype: HTMLWopVincentImgElement;
    new (): HTMLWopVincentImgElement;
  };
  interface HTMLElementTagNameMap {
    'wop-vincent-img': HTMLWopVincentImgElement;
  }
  interface ElementTagNameMap {
    'wop-vincent-img': HTMLWopVincentImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wop-vincent-img': JSXElements.WopVincentImgAttributes;
    }
  }
  namespace JSXElements {
    export interface WopVincentImgAttributes extends HTMLAttributes {
      'dataSrc'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface WopVincent {
      'delay': number;
      'play': () => void;
      'stop': () => void;
    }
  }

  interface HTMLWopVincentElement extends StencilComponents.WopVincent, HTMLStencilElement {}

  var HTMLWopVincentElement: {
    prototype: HTMLWopVincentElement;
    new (): HTMLWopVincentElement;
  };
  interface HTMLElementTagNameMap {
    'wop-vincent': HTMLWopVincentElement;
  }
  interface ElementTagNameMap {
    'wop-vincent': HTMLWopVincentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wop-vincent': JSXElements.WopVincentAttributes;
    }
  }
  namespace JSXElements {
    export interface WopVincentAttributes extends HTMLAttributes {
      'delay'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;